tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: ENGINEER
      database: TEMP
      schema: YUTLIU
      warehouse: SNOWHOUSE
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: ENGINEER
      database: TEMP
      schema: YUTLIU
      warehouse: SNOWHOUSE